import type { CreationEvent } from "@/features/company-creation/types";

export function buildCreationEvents(now: string): CreationEvent[] {
  return [
    {
      id: "ceo-assigned",
      type: "CEO_ASSIGNED",
      title: "AI CEO",
      description: "Analyzing mission...",
      status: "completed",
      timestamp: now,
    },
    {
      id: "research-ready",
      type: "RESEARCH_READY",
      title: "Research Department",
      description: "Assembling team...",
      status: "completed",
      department: "research",
      timestamp: now,
    },
    {
      id: "brand-ready",
      type: "BRAND_READY",
      title: "Brand Department",
      description: "Assembling team...",
      status: "completed",
      department: "brand",
      timestamp: now,
    },
    {
      id: "scripts-ready",
      type: "SCRIPTS_READY",
      title: "Script Department",
      description: "Assembling team...",
      status: "completed",
      department: "scripts",
      timestamp: now,
    },
    {
      id: "video-ready",
      type: "VIDEO_READY",
      title: "Video Department",
      description: "Assembling team...",
      status: "completed",
      department: "video",
      timestamp: now,
    },
    {
      id: "publishing-ready",
      type: "PUBLISHING_READY",
      title: "Publishing Department",
      description: "Assembling team...",
      status: "completed",
      department: "publishing",
      timestamp: now,
    },
    {
      id: "growth-ready",
      type: "GROWTH_READY",
      title: "Growth Department",
      description: "Assembling team...",
      status: "completed",
      department: "growth",
      timestamp: now,
    },
    {
      id: "workflow-created",
      type: "WORKFLOW_CREATED",
      title: "Workflow",
      description: "Execution pipeline ready",
      status: "completed",
      timestamp: now,
    },
    {
      id: "first-task-ready",
      type: "FIRST_TASK_READY",
      title: "Research niche and audience",
      description: "Ready to execute",
      status: "completed",
      department: "research",
      timestamp: now,
    },
  ];
}
